/*
@license
dhtmlxScheduler v.4.3.1 

This software is covered by DHTMLX Commercial License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
scheduler._props={},scheduler.createUnitsView=function(e,t,a,r,n,i,l){"object"==typeof e&&(a=e.list,t=e.property,r=e.size||0,n=e.step||1,i=e.skip_incorrect,l=e.days||1,e=e.name),scheduler._props[e]={map_to:t,options:a,step:n,position:0,days:l},r>scheduler._props[e].options.length&&(scheduler._props[e]._original_size=r,r=0),scheduler._props[e].size=r,scheduler._props[e].skip_incorrect=i||!1,scheduler.date[e+"_start"]=scheduler.date.day_start,scheduler.templates[e+"_date"]=function(t,a){var r=scheduler._props[e];

return r.days>1?scheduler.templates.week_date(t,a):scheduler.templates.day_date(t)},scheduler._get_unit_index=function(e,t){var a=e.position||0,r=Math.floor((scheduler._correct_shift(+t,1)-+scheduler._min_date)/864e5),n=e.options.length;return r>=n&&(r%=n),a+r},scheduler.templates[e+"_scale_text"]=function(e,t,a){return a.css?"<span class='"+a.css+"'>"+t+"</span>":t},scheduler.templates[e+"_scale_date"]=function(t){var a=scheduler._props[e],r=a.options;if(!r.length)return"";var n=scheduler._get_unit_index(a,t),i=r[n];

return scheduler.templates[e+"_scale_text"](i.key,i.label,i)},scheduler.templates[e+"_second_scale_date"]=function(e){return scheduler.templates.week_scale_date(e)},scheduler.date["add_"+e]=function(t,a){return scheduler.date.add(t,a*scheduler._props[e].days,"day")},scheduler.date["get_"+e+"_end"]=function(t){return scheduler.date.add(t,(scheduler._props[e].size||scheduler._props[e].options.length)*scheduler._props[e].days,"day")},scheduler.attachEvent("onOptionsLoad",function(){for(var t=scheduler._props[e],a=t.order={},r=t.options,n=0;n<r.length;n++)a[r[n].key]=n;

t._original_size&&0===t.size&&(t.size=t._original_size,delete t.original_size),t.size>r.length?(t._original_size=t.size,t.size=0):t.size=t._original_size||t.size,scheduler._date&&scheduler._mode==e&&scheduler.setCurrentView(scheduler._date,scheduler._mode)}),scheduler["mouse_"+e]=function(e){var t=scheduler._props[this._mode];if(t){if(e=this._week_indexes_from_pos(e),this._drag_event||(this._drag_event={}),this._drag_id&&this._drag_mode&&(this._drag_event._dhx_changed=!0),this._drag_mode&&"new-size"==this._drag_mode){
var a=scheduler._get_event_sday(scheduler._events[scheduler._drag_id]);Math.floor(e.x/t.options.length)!=Math.floor(a/t.options.length)&&(e.x=a)}var r=e.x%t.options.length,n=Math.min(r+t.position,t.options.length-1);e.section=(t.options[n]||{}).key,e.x=Math.floor(e.x/t.options.length);var i=this.getEvent(this._drag_id);this._update_unit_section({view:t,event:i,pos:e})}return e.force_redraw=!0,e},scheduler.callEvent("onOptionsLoad",[])},scheduler._update_unit_section=function(e){var t=e.view,a=e.event,r=e.pos;

a&&(a[t.map_to]=r.section)},scheduler.scrollUnit=function(e){var t=scheduler._props[this._mode];t&&(t.position=Math.min(Math.max(0,t.position+e),t.options.length-t.size),this.setCurrentView())},function(){var e=function(e){var t=scheduler._props[scheduler._mode];if(t&&t.order&&t.skip_incorrect){for(var a=[],r=0;r<e.length;r++)"undefined"!=typeof t.order[e[r][t.map_to]]&&a.push(e[r]);e.splice(0,e.length),e.push.apply(e,a)}return e},t=scheduler._pre_render_events_table;scheduler._pre_render_events_table=function(a,r){
return a=e(a),t.apply(this,[a,r])};var a=scheduler._pre_render_events_line;scheduler._pre_render_events_line=function(t,r){return t=e(t),a.apply(this,[t,r])};var r=function(e,t){if(e&&"undefined"==typeof e.order[t[e.map_to]]){var a=scheduler,r=864e5,n=Math.floor((t.end_date-a._min_date)/r);return e.options.length&&(t[e.map_to]=e.options[Math.min(n+e.position,e.options.length-1)].key),!0}},n=scheduler.is_visible_events;scheduler.is_visible_events=function(e){var t=n.apply(this,arguments);if(t){var a=scheduler._props[this._mode];

if(a&&a.size){var r=a.order[e[a.map_to]];if(r<a.position||r>=a.size+a.position)return!1}}return t};var i=scheduler._process_ignores;scheduler._process_ignores=function(e,t,a,r,n){if(!scheduler._props[this._mode])return void i.call(this,e,t,a,r,n);this._ignores={},this._ignores_detected=0;var l=scheduler["ignore_"+this._mode];if(l){var d=scheduler._props&&scheduler._props[this._mode]?scheduler._props[this._mode].size||scheduler._props[this._mode].options.length:1;t/=d;for(var s=new Date(e),o=0;t>o;o++){
if(l(s))for(var _=o*d,c=(o+1)*d,h=_;c>h;h++)this._ignores_detected+=1,this._ignores[h]=!0,n&&t++;s=scheduler.date.add(s,r,a),scheduler.date[a+"_start"]&&(s=scheduler.date[a+"_start"](s))}}};var l=scheduler._reset_scale;scheduler._reset_scale=function(){var e=scheduler._props[this._mode],t=l.apply(this,arguments);if(e){this._max_date=this.date.add(this._min_date,e.days,"day");for(var a=this._els.dhx_cal_data[0].childNodes,r=0;r<a.length;r++)a[r].className=a[r].className.replace("_now","");var n=new Date;

if(n.valueOf()>=this._min_date&&n.valueOf()<this._max_date){var i=864e5,d=Math.floor((n-scheduler._min_date)/i),s=e.options.length,o=d*s,_=o+s;for(r=o;_>r;r++)a[r]&&(a[r].className=a[r].className.replace("dhx_scale_holder","dhx_scale_holder_now"))}if(e.size&&e.size<e.options.length){var c=this._els.dhx_cal_header[0],h=document.createElement("DIV");e.position&&(h.className="dhx_cal_prev_button",h.style.cssText="left:1px;top:2px;position:absolute;",h.innerHTML="&nbsp;",c.firstChild.appendChild(h),h.onclick=function(){
scheduler.scrollUnit(-1*e.step)}),e.position+e.size<e.options.length&&(h=document.createElement("DIV"),h.className="dhx_cal_next_button",h.style.cssText="left:auto; right:0px;top:2px;position:absolute;",h.innerHTML="&nbsp;",c.lastChild.appendChild(h),h.onclick=function(){scheduler.scrollUnit(e.step)})}}return t};var d=scheduler._reset_scale;scheduler._reset_scale=function(){var e=scheduler._props[this._mode],t=scheduler.xy.scale_height;e&&e.days>1?this._header_resized||(this._header_resized=scheduler.xy.scale_height,
scheduler.xy.scale_height=2*t):this._header_resized&&(scheduler.xy.scale_height/=2,this._header_resized=!1),d.apply(this,arguments)};var s=scheduler._get_view_end;scheduler._get_view_end=function(){var e=scheduler._props[this._mode];if(e&&e.days>1){var t=this._get_timeunit_start();return scheduler.date.add(t,e.days,"day")}return s.apply(this,arguments)};var o=scheduler._render_x_header;scheduler._render_x_header=function(e,t,a,r){var n=scheduler._props[this._mode];if(!n||n.days<=1)return o.apply(this,arguments);

if(n.days>1){var i=scheduler.xy.scale_height;scheduler.xy.scale_height=Math.ceil(i/2),o.call(this,e,t,a,r,Math.ceil(scheduler.xy.scale_height));var l=n.options.length;if((e+1)%l===0){var d=document.createElement("DIV");d.className="dhx_scale_bar dhx_second_scale_bar";var s=this.date.add(this._min_date,Math.floor(e/l),"day");this.templates[this._mode+"_second_scalex_class"]&&(d.className+=" "+this.templates[this._mode+"_second_scalex_class"](new Date(s)));var _,c=this._cols[e]*l-1;_=l>1?this._colsS[e-(l-1)]-this.xy.scale_width-2:t,
this.set_xy(d,c,this.xy.scale_height-2,_,0),d.innerHTML=this.templates[this._mode+"_second_scale_date"](new Date(s),this._mode),r.appendChild(d)}scheduler.xy.scale_height=i}};var _=scheduler._get_event_sday;scheduler._get_event_sday=function(e){var t=scheduler._props[this._mode];if(t){if(t.days<=1)return r(t,e),this._get_section_sday(e[t.map_to]);var a=864e5,n=Math.floor((e.end_date.valueOf()-1-scheduler._min_date.valueOf())/a),i=t.options.length,l=t.order[e[t.map_to]];return n*i+l-t.position}return _.call(this,e);

},scheduler._get_section_sday=function(e){var t=scheduler._props[this._mode];return t.order[e]-t.position};var c=scheduler.locate_holder_day;scheduler.locate_holder_day=function(e,t,a){var n=scheduler._props[this._mode];if(n&&a){if(r(n,a),n.days<=1)return 1*n.order[a[n.map_to]]+(t?1:0)-n.position;var i=864e5,l=Math.floor((a.start_date.valueOf()-scheduler._min_date.valueOf())/i),d=n.options.length,s=n.order[a[n.map_to]];return l*d+1*s+(t?1:0)-n.position}return c.apply(this,arguments)};var h=scheduler._time_order;

scheduler._time_order=function(e){var t=scheduler._props[this._mode];t?e.sort(function(e,a){return t.order[e[t.map_to]]>t.order[a[t.map_to]]?1:-1}):h.apply(this,arguments)};var u=scheduler._pre_render_events_table;scheduler._pre_render_events_table=function(e,t){function a(e){var t=scheduler.date.add(e,1,"day");return t=scheduler.date.date_part(t)}var r=scheduler._props[this._mode];if(r&&r.days>1&&!this.config.all_timed){for(var n={},i=0;i<e.length;i++){var l=e[i];if(this.isOneDayEvent(e[i])){var d=+scheduler.date.date_part(new Date(l.start_date));

n[d]||(n[d]=[]),n[d].push(l)}else{var s=new Date(Math.min(+l.end_date,+this._max_date)),o=new Date(Math.max(+l.start_date,+this._min_date));for(e.splice(i,1);+s>+o;){var _=scheduler._lame_clone(l);_.start_date=o,_.end_date=a(_.start_date),o=scheduler.date.add(o,1,"day");var d=+scheduler.date.date_part(new Date(o));n[d]||(n[d]=[]),n[d].push(_),e.splice(i,0,_),i++}i--}}var c=[];for(var i in n)c.splice.apply(c,[c.length-1,0].concat(u.apply(this,[n[i],t])));for(var i=0;i<c.length;i++)this._ignores[c[i]._sday]?(c.splice(i,1),
i--):c[i]._first_chunk=c[i]._last_chunk=!1;c.sort(function(e,t){return e.start_date.valueOf()==t.start_date.valueOf()?e.id>t.id?1:-1:e.start_date>t.start_date?1:-1}),e=c}else e=u.apply(this,[e,t]);return e},scheduler.attachEvent("onEventAdded",function(e,t){if(this._loading)return!0;for(var a in scheduler._props){var r=scheduler._props[a];"undefined"==typeof t[r.map_to]&&(t[r.map_to]=r.options[0].key)}return!0}),scheduler.attachEvent("onEventCreated",function(e,t){var a=scheduler._props[this._mode];

if(a&&t){var n=this.getEvent(e),i=this._mouse_coords(t);this._update_unit_section({view:a,event:n,pos:i}),r(a,n),this.event_updated(n)}return!0})}();
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_units.js.map