/*
@license
dhtmlxScheduler v.4.3.1 

This software is covered by DHTMLX Commercial License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
scheduler._wa={},scheduler.xy.week_agenda_scale_height=20,scheduler.templates.week_agenda_event_text=function(e,t,a,r){return scheduler.templates.event_date(e)+" "+a.text},scheduler.date.week_agenda_start=scheduler.date.week_start,scheduler.date.week_agenda_end=function(e){return scheduler.date.add(e,7,"day")},scheduler.date.add_week_agenda=function(e,t){return scheduler.date.add(e,7*t,"day")},scheduler.attachEvent("onSchedulerReady",function(){var e=scheduler.templates;e.week_agenda_date||(e.week_agenda_date=e.week_date);

}),function(){var e=scheduler.date.date_to_str("%l, %F %d");scheduler.templates.week_agenda_scale_date=function(t){return e(t)}}(),scheduler.attachEvent("onTemplatesReady",function(){scheduler.attachEvent("onSchedulerResize",function(){return"week_agenda"==this._mode?(this.week_agenda_view(!0),!1):!0});var e=scheduler.render_data;scheduler.render_data=function(t){return"week_agenda"!=this._mode?e.apply(this,arguments):void scheduler.week_agenda_view(!0)};var t=function(){scheduler._cols=[];var e=parseInt(scheduler._els.dhx_cal_data[0].style.width);

scheduler._cols.push(Math.floor(e/2)),scheduler._cols.push(e-scheduler._cols[0]-1),scheduler._colsS={0:[],1:[]};for(var t=parseInt(scheduler._els.dhx_cal_data[0].style.height),a=0;3>a;a++)scheduler._colsS[0].push(Math.floor(t/(3-scheduler._colsS[0].length))),t-=scheduler._colsS[0][a];scheduler._colsS[1].push(scheduler._colsS[0][0]),scheduler._colsS[1].push(scheduler._colsS[0][1]),t=scheduler._colsS[0][scheduler._colsS[0].length-1],scheduler._colsS[1].push(Math.floor(t/2)),scheduler._colsS[1].push(t-scheduler._colsS[1][scheduler._colsS[1].length-1]);

},a=function(){t(),scheduler._els.dhx_cal_data[0].innerHTML="",scheduler._rendered=[];for(var e="",a=0;2>a;a++){var r=scheduler._cols[a],n="dhx_wa_column";1==a&&(n+=" dhx_wa_column_last"),e+="<div class='"+n+"' style='width: "+r+"px;'>";for(var d=0;d<scheduler._colsS[a].length;d++){var i=scheduler.xy.week_agenda_scale_height-2,l=scheduler._colsS[a][d]-i-2,s=Math.min(6,2*d+a);e+="<div class='dhx_wa_day_cont'><div style='height:"+i+"px; line-height:"+i+"px;' class='dhx_wa_scale_bar'></div><div style='height:"+l+"px;' class='dhx_wa_day_data' day='"+s+"'></div></div>";

}e+="</div>"}scheduler._els.dhx_cal_date[0].innerHTML=scheduler.templates[scheduler._mode+"_date"](scheduler._min_date,scheduler._max_date,scheduler._mode),scheduler._els.dhx_cal_data[0].innerHTML=e;for(var o=scheduler._els.dhx_cal_data[0].getElementsByTagName("div"),_=[],a=0;a<o.length;a++)"dhx_wa_day_cont"==o[a].className&&_.push(o[a]);scheduler._wa._selected_divs=[];for(var c=scheduler.get_visible_events(),h=scheduler.date.week_start(scheduler._date),u=scheduler.date.add(h,1,"day"),a=0;7>a;a++){
_[a]._date=h;var p=_[a].childNodes[0],v=_[a].childNodes[1];p.innerHTML=scheduler.templates.week_agenda_scale_date(h);for(var m=[],g=0;g<c.length;g++){var f=c[g];f.start_date<u&&f.end_date>h&&m.push(f)}m.sort(function(e,t){return e.start_date.valueOf()==t.start_date.valueOf()?e.id>t.id?1:-1:e.start_date>t.start_date?1:-1});for(var d=0;d<m.length;d++){var y=m[d],b=document.createElement("div");scheduler._rendered.push(b);var x=scheduler.templates.event_class(y.start_date,y.end_date,y);b.className="dhx_wa_ev_body"+(x?" "+x:""),
y._text_style&&(b.style.cssText=y._text_style),y.color&&(b.style.background=y.color),y.textColor&&(b.style.color=y.textColor),scheduler._select_id&&y.id==scheduler._select_id&&(scheduler.config.week_agenda_select||void 0===scheduler.config.week_agenda_select)&&(b.className+=" dhx_cal_event_selected",scheduler._wa._selected_divs.push(b));var k="";y._timed||(k="middle",y.start_date.valueOf()>=h.valueOf()&&y.start_date.valueOf()<=u.valueOf()&&(k="start"),y.end_date.valueOf()>=h.valueOf()&&y.end_date.valueOf()<=u.valueOf()&&(k="end")),
b.innerHTML=scheduler.templates.week_agenda_event_text(y.start_date,y.end_date,y,h,k),b.setAttribute("event_id",y.id),v.appendChild(b)}h=scheduler.date.add(h,1,"day"),u=scheduler.date.add(u,1,"day")}};scheduler.week_agenda_view=function(e){scheduler._min_date=scheduler.date.week_start(scheduler._date),scheduler._max_date=scheduler.date.add(scheduler._min_date,1,"week"),scheduler.set_sizes(),e?(scheduler._table_view=scheduler._allow_dnd=!0,void 0===scheduler._wa._prev_data_border&&(scheduler._wa._prev_data_border=scheduler._els.dhx_cal_data[0].style.borderTopWidth),
scheduler._els.dhx_cal_data[0].style.borderTopWidth=0,scheduler._els.dhx_cal_data[0].style.overflowY="hidden",scheduler._els.dhx_cal_date[0].innerHTML="",scheduler._els.dhx_cal_data[0].style.top=parseInt(scheduler._els.dhx_cal_data[0].style.top)-20-1+"px",scheduler._els.dhx_cal_data[0].style.height=parseInt(scheduler._els.dhx_cal_data[0].style.height)+20+1+"px",scheduler._els.dhx_cal_header[0].style.display="none",a()):(scheduler._table_view=scheduler._allow_dnd=!1,void 0!==scheduler._wa._prev_data_border&&(scheduler._els.dhx_cal_data[0].style.borderTopWidth=scheduler._wa._prev_data_border,
delete scheduler._wa._prev_data_border),scheduler._els.dhx_cal_data[0].style.overflowY="auto",scheduler._els.dhx_cal_data[0].style.top=parseInt(scheduler._els.dhx_cal_data[0].style.top)+20+"px",scheduler._els.dhx_cal_data[0].style.height=parseInt(scheduler._els.dhx_cal_data[0].style.height)-20+"px",scheduler._els.dhx_cal_header[0].style.display="block")},scheduler.mouse_week_agenda=function(e){for(var t,a=e.ev,r=a.srcElement||a.target;r.parentNode;)r._date&&(t=r._date),r=r.parentNode;if(!t)return e;

e.x=0;var n=t.valueOf()-scheduler._min_date.valueOf();if(e.y=Math.ceil(n/6e4/this.config.time_step),"move"==this._drag_mode&&this._drag_pos&&this._is_pos_changed(this._drag_pos,e)){var d;this._drag_event._dhx_changed=!0,this._select_id=this._drag_id;for(var i=0;i<scheduler._rendered.length;i++)scheduler._drag_id==this._rendered[i].getAttribute("event_id")&&(d=this._rendered[i]);if(!scheduler._wa._dnd){var l=d.cloneNode(!0);this._wa._dnd=l,l.className=d.className,l.id="dhx_wa_dnd",l.className+=" dhx_wa_dnd",
document.body.appendChild(l)}var s=document.getElementById("dhx_wa_dnd");s.style.top=(a.pageY||a.clientY)+20+"px",s.style.left=(a.pageX||a.clientX)+20+"px"}return e},scheduler.attachEvent("onBeforeEventChanged",function(e,t,a){if("week_agenda"==this._mode&&"move"==this._drag_mode){var r=document.getElementById("dhx_wa_dnd");r.parentNode.removeChild(r),scheduler._wa._dnd=!1}return!0}),scheduler.attachEvent("onEventSave",function(e,t,a){return a&&"week_agenda"==this._mode&&(this._select_id=e),!0}),
scheduler._wa._selected_divs=[],scheduler.attachEvent("onClick",function(e,t){if("week_agenda"==this._mode&&(scheduler.config.week_agenda_select||void 0===scheduler.config.week_agenda_select)){if(scheduler._wa._selected_divs)for(var a=0;a<this._wa._selected_divs.length;a++){var r=this._wa._selected_divs[a];r.className=r.className.replace(/ dhx_cal_event_selected/,"")}return this.for_rendered(e,function(e){e.className+=" dhx_cal_event_selected",scheduler._wa._selected_divs.push(e)}),scheduler._select_id=e,
!1}return!0})});
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_week_agenda.js.map